### PR TITLE
No prompt

### PR DESCRIPTION
**Pull request by freaker2k7**
Please remove the prompts so that your great playbook can be used in CI and automated processes that can't type YES.

### CODE REVIEW

**Comment by ilias-sp** [comment]
hey @freaker2k7 !

thanks for the proposal, but you can skip the "confirmation" pre_task by supplying `-e confirmation=YES` in your `ansible-playbook` command. 

i would like to keep this pre_task, so that users have one last chance to think before they run the playbooks :)

**Comment by ilias-sp** [comment]
but i will add this clarification in the Readme though

**Comment by freaker2k7** [comment]
Thank you.

Also, please add a step for installing sshpass, you call it but it might not be present.

**Comment by freaker2k7** [comment]
I tested your theory, but it still prompts...

Maybe add an "if" ?!

**Comment by ilias-sp** [comment]
are you doing it as below? 

```
[http_offline@greenhat-29 ansible-setup-passwordless-ssh]$ cat test.yml                        
---
- hosts: local_host
  gather_facts: false
  vars_prompt:
    - name: confirmation
      prompt: "Type 'YES' to establish passwordless login to the remote hosts:"
      default: 'NO'
      private: no
      when: confirmation != "YES"
  pre_tasks:
    - name: "Check Confirmation"
      fail: msg="Exiting... You must type 'YES' to continue."
      when: confirmation != "YES"

  tasks:

    - debug:
        msg: "running stuff now.."

[http_offline@greenhat-29 ansible-setup-passwordless-ssh]$ ansible-playbook -i hosts test.yml 
Type 'YES' to establish passwordless login to the remote hosts: [NO]: ^C [ERROR]: User interrupted execution

[http_offline@greenhat-29 ansible-setup-passwordless-ssh]$ ansible-playbook -i hosts test.yml -e confirmation=YES

PLAY [local_host] ******************************************************************************************************************************************************************************************************

TASK [Check Confirmation] **********************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [debug] ***********************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "running stuff now.."
}

PLAY RECAP *************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

[http_offline@greenhat-29 ansible-setup-passwordless-ssh]$ 
```

about installing the sshpass, its increases the complexity and its not in the scope of this PB. but i added code to check if sshpass is available in the machine, and if not fail the execution. pushing it now..

**Comment by freaker2k7** [comment]
Oh... I'm calling it in a playbook using import_playbook

**Comment by ilias-sp** [comment]
i tried tweaking this `vars_prompt` step with a var in the inventory file, but its not working as intended :( we can either remove it entirely as you said, or keep it as is. Or have both PBs in the repository :) we can do that instead i guess

**Comment by freaker2k7** [comment]
I'd prefer to remove it as it's a totally optional step and I'd like using the main repo :)

**Comment by ilias-sp** [comment]
> Oh... I'm calling it in a playbook using import_playbook

can you try the import_playbook task with `environment` clause?:

```
- hosts: dev
  tasks:
    - name: Echo my_env_var
      shell: "echo $MY_ENV_VARIABLE"
      environment:
        MY_ENV_VARIABLE: whatever_value
```

**Comment by ilias-sp** [comment]
please ignore previous comment. environment variables are not ansible vars, it wont work

**Comment by freaker2k7** [comment]
Nope... I've set

```
- name: sync-ssh
  environment:
    confirmation: "YES"
  import_playbook: ../../plays/thirdparty/ansible-setup-passwordless-ssh/ansible-setup-passwordless-ssh.yml
```

**Comment by freaker2k7** [comment]
Maybe create a git tag "safe" and the prompt can remain there,
or an "unsafe" tag without the prompt.

What do you think ?

**Comment by ilias-sp** [comment]
please check [https://serverfault.com/questions/797896/passing-variables-from-one-included-ansible-playbook-to-another](https://serverfault.com/questions/797896/passing-variables-from-one-included-ansible-playbook-to-another)

it says you can pass the `-e confirmation=YES` to the playbook that imports the PB. i did a simple step and it works :)

the 2 tags would be tricky, i would prefer to duplicate the 2 PBs to safe/unsafe, its easier for people downloading the master repo..

**Comment by freaker2k7** [comment]
I can't alter the ansible cli that much because it's run from Jenkins as a part of our CI,
so to pass a global env. var. would be a mess and I have no idea what it will influence.

If some other role (let's say from galaxy or git) uses "confirmation" as well, that will lead to unexpected behavior.

**Comment by freaker2k7** [comment]
Another way to solve it delicately, is to cut this part (I've deleted in my commit) into another file,
let's call it prompter.yml and in the main.yml call import this task if there in no (simple) variable called "confirmation".

What do you think ?

**Comment by ilias-sp** [comment]
the problem is that ansible - by design - doesnt allow interactive tasks , please see [here](https://stackoverflow.com/questions/25466675/ansible-to-conditionally-prompt-for-a-variable) if interested.

to cut story short, there is no easy solution to keep the best of both worlds. i will add the "unsafe" PBs in the main repo as well. and we are done :) i dont expect much changes in the future anyways .. :)

**Comment by freaker2k7** [comment]
Thank you. +2

**Pull request merged**
